apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: order-platform
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      serviceAccountName: notification-service
      containers:
        - name: notification-service
          image: order-platform/notification-service:local
          ports:
            - containerPort: 8083
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
          resources:
            requests:
              memory: 192Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 400m
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: order-platform
spec:
  selector:
    app: notification-service
  ports:
    - port: 8083
      targetPort: 8083
